sample_app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "static_pages/home"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "password_resets/new"
    get "password_resets/edit"
    get "/users/:id/following", to: "following#index", as: "following"
    get "/users/:id/followers", to: "followers#index", as: "followers"
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

sample_app/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    <%= t "shared.the_form_contains", error: object.errors.count %>
    <%= pluralize object.errors.count, t("shared.error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <%= link_to t(".sample_app"), root_path, id: "logo", class: "nav-link" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
        <li class="nav-item"><%= link_to t(".users"), users_path %></li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" > <%= t ".account" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to t(".profile"), user_path(locale, current_user), class: "dropdown-item" %></li>
            <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t(".log_out"), logout_path, method: :delete, class: "dropdown-item" %> </li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to t(".login"), login_path(locale), class: "nav-link" %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

sample_app/app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 mt-4 ml-4">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      <strong>
        <%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
      </strong>
    </div>
    <script>
      $(".alert").alert();
    </script>
  <% end %>
  </div>
</div>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> | <%= t "title" %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>