sample_app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "static_pages/home"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "password_resets/new"
    get "password_resets/edit"
    get "/users/:id/following", to: "following#index", as: "following"
    get "/users/:id/followers", to: "followers#index", as: "followers"
    resources :users do
        member do
            get :following, :followers
        end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

sample_app/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, params: {controller: :static_pages, action: :home} %>
<% end %>

sample_app/app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "layouts/errors", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t("microposts.content.placeholder") %>
  </div>
  <span class="image">
    <%= f.file_field :image, accept: Settings.image.valid_input %>
  </span>
  <%= f.submit t(".post"), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  const prompt = "<%= t "microposts.oversize_alert" %>"
</script>
<%= javascript_pack_tag "micropost", "data-turbolinks-track": "reload" %>

sample_app/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_path(@user) %>">
  <strong id="following" class="stat">
    <%= @user.following.size %>
  </strong>
  <%= t("user.stats.following") %>
  </a>
  <a href="<%= followers_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "user.stats.followers" %>
  </a>
</div>

sample_app/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.shared.user_info_length), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".view _my_profile"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t(".micropost") %></span>